volumes:
  postgres_local_data:
    driver: local

services:
  postgres:
    restart: always
    image: postgres:17
    volumes:
      - postgres_local_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
