volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  mongo_data:
    driver: local
  logs:
    driver: local

networks:
  mongo_network:
    driver: bridge
  caddy_network:
    driver: bridge

services:
  finance:
    depends_on:
      mongo:
        condition: service_started
    restart: always
    image: finance:latest
    build:
      context: .
      args:
        APP_PATH: finance
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./logs/finance:/logs/finance
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - caddy_network
      - mongo_network
    environment:
      PORT: "8000"
      MONGO_USER: ${MONGO_ADMIN_USER}
      MONGO_PASS: ${MONGO_ADMIN_PASS}

  caddy:
    depends_on:
      - finance
    restart: unless-stopped
    image: caddy/caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy_network

  mongo:
    restart: always
    image: mongo:8.0.4
    volumes:
      - mongo_data:/data/db
    ports:
      - "127.0.0.1:27017:27017"
    networks:
      - mongo_network
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ADMIN_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ADMIN_PASS}

  mongo-express:
    links:
      - mongo
    restart: always
    image: mongo-express:latest
    volumes:
      - mongo_data:/data/db
    networks:
      - mongo_network
    ports:
      - "127.0.0.1:8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: "mongo"
      ME_CONFIG_MONGODB_PORT: "27017"
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ADMIN_USER}:${MONGO_ADMIN_PASS}@mongo:27017/
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_WEB_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_WEB_PASS}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ADMIN_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ADMIN_PASS}
