volumes:
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  postgres_data:
    driver: local
  logs:
    driver: local

networks:
  postgres_network:
    driver: bridge
  caddy_network:
    driver: bridge

services:
  finance:
    depends_on:
      postgres:
        condition: service_started
    restart: always
    image: gvabal/finance:latest
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - ./logs/finance:/logs/finance
    ports:
      - "127.0.0.1:8000:8000"
    networks:
      - caddy_network
      - postgres_network
    environment:
      PORT: "8000"
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASS: ${POSTGRES_PASS}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}

  caddy:
    depends_on:
      - finance
    restart: unless-stopped
    image: caddy/caddy:latest
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    networks:
      - caddy_network

  postgres:
    restart: always
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - postgres_network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
