services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.myresolvertwo.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolvertwo.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.myresolvertwo.acme.storage=/letsencrypt/acme2.json"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.app.address=:90"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.app.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.app.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "90:90"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: web:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=Host(`vabalas.my.id`)"
      - "traefik.http.routers.web.entrypoints=websecure"
    environment:
      PORT: "80"
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  app:
    image: app:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=90"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolvertwo"
      - "traefik.http.routers.app.rule=Host(`vabalas.my.id`) && Path(`/api`)"
    environment:
      PORT: "90"
    expose:
      - 90
    deploy:
      mode: replicated
      replicas: 1
    restart: always
volumes:
  letsencrypt:
