services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - public
  web:
    image: web:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=Host(`vabalas.my.id`)"
      - "traefik.http.routers.web.entrypoints=websecure"
    environment:
      PORT: "80"
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - public
      - private
  app:
    image: app:prod
    environment:
      PORT: "90"
    expose:
      - 90
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    networks:
      - private

volumes:
  letsencrypt:

networks:
  public:
  private:
    internal: true