services:
  frontend:
    image: web:prod
    environment:
      PORT: "80"
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  backend:
    image: app:prod
    environment:
      PORT: "90"
    expose:
      - 90
    deploy:
      mode: replicated
      replicas: 1
    restart: always
