services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--log.level=DEBUG"
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.webinsecure.address=:80"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: web:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.web.tls=true"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.routers.web.rule=Host(`vabalas.my.id`)"
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.middlewares.redirect-to-index.errors.status=404"
      - "traefik.http.middlewares.redirect-to-index.errors.query=./index.html"
    environment:
      PORT: "80"
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  app:
    image: app:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.routers.app.rule=Host(`api.vabalas.my.id`)"
      - "traefik.http.routers.app.entrypoints=websecure"
    environment:
      PORT: "90"
    expose:
      - 90
    deploy:
      mode: replicated
      replicas: 1
    restart: always
volumes:
  letsencrypt:
