services:
  reverse-proxy:
    restart: always
    image: traefik:v3.2.0
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 1.0
          memory: 7680m
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--entryPoints.websecure.address=:443"
      - "--entrypoints.webinsecure.address=:80"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.webinsecure.http.redirections.entrypoint.permanent=true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  website:
    depends_on:
      - reverse-proxy
    restart: always
    image: website:prod
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: 1.0
          memory: 7680m
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.app.tls=true"
      - "traefik.http.routers.app.tls.certresolver=le"
      - "traefik.http.routers.app.rule=Host(`vabalas.my.id`)"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.middlewares=cors"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworiginlist=https://vabalas.my.id"
      - "traefik.http.middlewares.cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.cors.headers.addvaryheader=true"
    environment:
      PORT: "8080"
    expose:
      - 8080
volumes:
  letsencrypt:
