services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=vabalas@vabalas.my.id"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: web:prod
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.http.routers.site.tls=true"
      - "traefik.http.routers.app.tls.certresolver=myresolver"
      - "traefik.http.routers.app.rule=Host(`vabalas.my.id`)"
      - "traefik.http.routers.app.entrypoints=websecure"
    environment:
      PORT: "80"
    expose:
      - 80
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  app:
    image: app:prod
    environment:
      PORT: "8080"
    expose:
      - 8080
    deploy:
      mode: replicated
      replicas: 1
    restart: always
    healthcheck:
      test: "curl --fail --silent 127.0.0.1/actuator/health | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
volumes:
  letsencrypt:
