server:
  port: ${PORT:8080}

spring:
  application:
    name: app
  docker:
    compose:
      enabled: false
  threads:
    virtual:
      enabled: true
  ai:
    openai:
      api-key: ${OPENAI_API_KEY:change-me}
      chat:
        options:
          model: gpt-4o-mini

gg:
  jte:
    usePrecompiledTemplates: true
