server:
  port: ${PORT}

spring:
  application:
    name: finance
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASS}@mongo:27017/finance?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: health
