micronaut:
  application:
    name: finance
  router:
    static-resources:
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  server:
    port: ${PORT:8080}

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    schema: finance
    schema-generate: CREATE_DROP
    password: ${POSTGRES_PASS:changeme}
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/postgres
    username: ${POSTGRES_USER:sa}

endpoints:
  all:
    enabled: true
    sensitive: false
