micronaut:
  application:
    name: finance
  router:
    static-resources:
      swagger:
        mapping: /swagger/**
        paths: classpath:META-INF/swagger
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui

datasources:
  default:
    db-type: postgres
    dialect: POSTGRES
    driver-class-name: org.postgresql.Driver
    schema-generate: create_drop
    password: ${POSTGRES_PASS:changeme}
    url: jdbc:postgresql://localhost:5432/postgres
    username: ${POSTGRES_USER:sa}

endpoints:
  all:
    enabled: true
    sensitive: false

flyway:
  datasources:
    default:
      enabled: true
      create-schemas: true
      default-schema: finance
