server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/nice-quotes?authSource=admin

management:
  endpoints:
    web:
      exposure:
        include: "*"