server:
  port: ${PORT:8080}

spring:
  application:
    name: api
  datasource:
    username: ${DB_USER}
    password: ${DB_PASS}
  flyway:
    default-schema: backend
  jpa:
    hibernate:
      ddl-auto: none
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: true
